// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AcquisitionManagerService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ipc.Definitions {

  /// <summary>Holder for reflection information generated from AcquisitionManagerService.proto</summary>
  public static partial class AcquisitionManagerServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for AcquisitionManagerService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AcquisitionManagerServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9BY3F1aXNpdGlvbk1hbmFnZXJTZXJ2aWNlLnByb3RvEg9pcGNfZGVmaW5p",
            "dGlvbnMaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byIiCgxTdGFydFJl",
            "cXVlc3QSEgoKc2FtcGxlTmFtZRgBIAEoCSINCgtTdG9wUmVxdWVzdCIcCgpT",
            "dGFydFJlcGx5Eg4KBnJlc3VsdBgBIAEoCCIbCglTdG9wUmVwbHkSDgoGcmVz",
            "dWx0GAEgASgIIjMKFkN1cnJlbnRTYW1wbGVOYW1lUmVwbHkSGQoRY3VycmVu",
            "dFNhbXBsZU5hbWUYASABKAkioQEKFUFjcXVpc2l0aW9uU3RhdGVSZXBseRJZ",
            "ChRhY3F1aXNpdGlvblN0YXRlRW51bRgBIAEoDjI7LmlwY19kZWZpbml0aW9u",
            "cy5BY3F1aXNpdGlvblN0YXRlUmVwbHkuQWNxdWlzaXRpb25TdGF0ZUVudW0i",
            "LQoUQWNxdWlzaXRpb25TdGF0ZUVudW0SCAoESURMRRAAEgsKB1JVTk5JTkcQ",
            "ASKBAgofQWNxdWlzaXRpb25Db21wbGV0aW9uU3RhdGVSZXBseRJ3Ch5hY3F1",
            "aXNpdGlvbkNvbXBsZXRpb25TdGF0ZUVudW0YASABKA4yTy5pcGNfZGVmaW5p",
            "dGlvbnMuQWNxdWlzaXRpb25Db21wbGV0aW9uU3RhdGVSZXBseS5BY3F1aXNp",
            "dGlvbkNvbXBsZXRpb25TdGF0ZUVudW0iZQoeQWNxdWlzaXRpb25Db21wbGV0",
            "aW9uU3RhdGVFbnVtEg4KCklOQ09NUExFVEUQABILCgdTVE9QUEVEEAESCgoG",
            "RkFJTEVEEAISGgoWU1VDQ0VTU0ZVTExZX0NPTVBMRVRFRBADMoAGChlBY3F1",
            "aXNpdGlvbk1hbmFnZXJTZXJ2aWNlEkUKBVN0YXJ0Eh0uaXBjX2RlZmluaXRp",
            "b25zLlN0YXJ0UmVxdWVzdBobLmlwY19kZWZpbml0aW9ucy5TdGFydFJlcGx5",
            "IgASQgoEU3RvcBIcLmlwY19kZWZpbml0aW9ucy5TdG9wUmVxdWVzdBoaLmlw",
            "Y19kZWZpbml0aW9ucy5TdG9wUmVwbHkiABJZChRHZXRDdXJyZW50U2FtcGxl",
            "TmFtZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRonLmlwY19kZWZpbml0aW9u",
            "cy5DdXJyZW50U2FtcGxlTmFtZVJlcGx5IgASYQoaR2V0Q3VycmVudFNhbXBs",
            "ZU5hbWVTdHJlYW0SFi5nb29nbGUucHJvdG9idWYuRW1wdHkaJy5pcGNfZGVm",
            "aW5pdGlvbnMuQ3VycmVudFNhbXBsZU5hbWVSZXBseSIAMAESVwoTR2V0QWNx",
            "dWlzaXRpb25TdGF0ZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRomLmlwY19k",
            "ZWZpbml0aW9ucy5BY3F1aXNpdGlvblN0YXRlUmVwbHkiABJfChlHZXRBY3F1",
            "aXNpdGlvblN0YXRlU3RyZWFtEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiYu",
            "aXBjX2RlZmluaXRpb25zLkFjcXVpc2l0aW9uU3RhdGVSZXBseSIAMAESawod",
            "R2V0QWNxdWlzaXRpb25Db21wbGV0aW9uU3RhdGUSFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaMC5pcGNfZGVmaW5pdGlvbnMuQWNxdWlzaXRpb25Db21wbGV0",
            "aW9uU3RhdGVSZXBseSIAEnMKI0dldEFjcXVpc2l0aW9uQ29tcGxldGlvblN0",
            "YXRlU3RyZWFtEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjAuaXBjX2RlZmlu",
            "aXRpb25zLkFjcXVpc2l0aW9uQ29tcGxldGlvblN0YXRlUmVwbHkiADABQhKq",
            "Ag9JcGMuRGVmaW5pdGlvbnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.StartRequest), global::Ipc.Definitions.StartRequest.Parser, new[]{ "SampleName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.StopRequest), global::Ipc.Definitions.StopRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.StartReply), global::Ipc.Definitions.StartReply.Parser, new[]{ "Result" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.StopReply), global::Ipc.Definitions.StopReply.Parser, new[]{ "Result" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.CurrentSampleNameReply), global::Ipc.Definitions.CurrentSampleNameReply.Parser, new[]{ "CurrentSampleName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.AcquisitionStateReply), global::Ipc.Definitions.AcquisitionStateReply.Parser, new[]{ "AcquisitionStateEnum" }, null, new[]{ typeof(global::Ipc.Definitions.AcquisitionStateReply.Types.AcquisitionStateEnum) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.Definitions.AcquisitionCompletionStateReply), global::Ipc.Definitions.AcquisitionCompletionStateReply.Parser, new[]{ "AcquisitionCompletionStateEnum" }, null, new[]{ typeof(global::Ipc.Definitions.AcquisitionCompletionStateReply.Types.AcquisitionCompletionStateEnum) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StartRequest : pb::IMessage<StartRequest> {
    private static readonly pb::MessageParser<StartRequest> _parser = new pb::MessageParser<StartRequest>(() => new StartRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRequest(StartRequest other) : this() {
      sampleName_ = other.sampleName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartRequest Clone() {
      return new StartRequest(this);
    }

    /// <summary>Field number for the "sampleName" field.</summary>
    public const int SampleNameFieldNumber = 1;
    private string sampleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SampleName {
      get { return sampleName_; }
      set {
        sampleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SampleName != other.SampleName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SampleName.Length != 0) hash ^= SampleName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SampleName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SampleName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SampleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SampleName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartRequest other) {
      if (other == null) {
        return;
      }
      if (other.SampleName.Length != 0) {
        SampleName = other.SampleName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SampleName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StopRequest : pb::IMessage<StopRequest> {
    private static readonly pb::MessageParser<StopRequest> _parser = new pb::MessageParser<StopRequest>(() => new StopRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StopRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopRequest(StopRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopRequest Clone() {
      return new StopRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StopRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StopRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StopRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class StartReply : pb::IMessage<StartReply> {
    private static readonly pb::MessageParser<StartReply> _parser = new pb::MessageParser<StartReply>(() => new StartReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartReply(StartReply other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartReply Clone() {
      return new StartReply(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private bool result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != false) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != false) {
        output.WriteRawTag(8);
        output.WriteBool(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartReply other) {
      if (other == null) {
        return;
      }
      if (other.Result != false) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StopReply : pb::IMessage<StopReply> {
    private static readonly pb::MessageParser<StopReply> _parser = new pb::MessageParser<StopReply>(() => new StopReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StopReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopReply(StopReply other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopReply Clone() {
      return new StopReply(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private bool result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StopReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StopReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != false) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != false) {
        output.WriteRawTag(8);
        output.WriteBool(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StopReply other) {
      if (other == null) {
        return;
      }
      if (other.Result != false) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CurrentSampleNameReply : pb::IMessage<CurrentSampleNameReply> {
    private static readonly pb::MessageParser<CurrentSampleNameReply> _parser = new pb::MessageParser<CurrentSampleNameReply>(() => new CurrentSampleNameReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CurrentSampleNameReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CurrentSampleNameReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CurrentSampleNameReply(CurrentSampleNameReply other) : this() {
      currentSampleName_ = other.currentSampleName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CurrentSampleNameReply Clone() {
      return new CurrentSampleNameReply(this);
    }

    /// <summary>Field number for the "currentSampleName" field.</summary>
    public const int CurrentSampleNameFieldNumber = 1;
    private string currentSampleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CurrentSampleName {
      get { return currentSampleName_; }
      set {
        currentSampleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CurrentSampleNameReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CurrentSampleNameReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentSampleName != other.CurrentSampleName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentSampleName.Length != 0) hash ^= CurrentSampleName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CurrentSampleName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CurrentSampleName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CurrentSampleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentSampleName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CurrentSampleNameReply other) {
      if (other == null) {
        return;
      }
      if (other.CurrentSampleName.Length != 0) {
        CurrentSampleName = other.CurrentSampleName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CurrentSampleName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AcquisitionStateReply : pb::IMessage<AcquisitionStateReply> {
    private static readonly pb::MessageParser<AcquisitionStateReply> _parser = new pb::MessageParser<AcquisitionStateReply>(() => new AcquisitionStateReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AcquisitionStateReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionStateReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionStateReply(AcquisitionStateReply other) : this() {
      acquisitionStateEnum_ = other.acquisitionStateEnum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionStateReply Clone() {
      return new AcquisitionStateReply(this);
    }

    /// <summary>Field number for the "acquisitionStateEnum" field.</summary>
    public const int AcquisitionStateEnumFieldNumber = 1;
    private global::Ipc.Definitions.AcquisitionStateReply.Types.AcquisitionStateEnum acquisitionStateEnum_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ipc.Definitions.AcquisitionStateReply.Types.AcquisitionStateEnum AcquisitionStateEnum {
      get { return acquisitionStateEnum_; }
      set {
        acquisitionStateEnum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AcquisitionStateReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AcquisitionStateReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AcquisitionStateEnum != other.AcquisitionStateEnum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AcquisitionStateEnum != 0) hash ^= AcquisitionStateEnum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AcquisitionStateEnum != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AcquisitionStateEnum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AcquisitionStateEnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AcquisitionStateEnum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AcquisitionStateReply other) {
      if (other == null) {
        return;
      }
      if (other.AcquisitionStateEnum != 0) {
        AcquisitionStateEnum = other.AcquisitionStateEnum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            acquisitionStateEnum_ = (global::Ipc.Definitions.AcquisitionStateReply.Types.AcquisitionStateEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AcquisitionStateReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum AcquisitionStateEnum {
        [pbr::OriginalName("IDLE")] Idle = 0,
        [pbr::OriginalName("RUNNING")] Running = 1,
      }

    }
    #endregion

  }

  public sealed partial class AcquisitionCompletionStateReply : pb::IMessage<AcquisitionCompletionStateReply> {
    private static readonly pb::MessageParser<AcquisitionCompletionStateReply> _parser = new pb::MessageParser<AcquisitionCompletionStateReply>(() => new AcquisitionCompletionStateReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AcquisitionCompletionStateReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.Definitions.AcquisitionManagerServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionCompletionStateReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionCompletionStateReply(AcquisitionCompletionStateReply other) : this() {
      acquisitionCompletionStateEnum_ = other.acquisitionCompletionStateEnum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AcquisitionCompletionStateReply Clone() {
      return new AcquisitionCompletionStateReply(this);
    }

    /// <summary>Field number for the "acquisitionCompletionStateEnum" field.</summary>
    public const int AcquisitionCompletionStateEnumFieldNumber = 1;
    private global::Ipc.Definitions.AcquisitionCompletionStateReply.Types.AcquisitionCompletionStateEnum acquisitionCompletionStateEnum_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ipc.Definitions.AcquisitionCompletionStateReply.Types.AcquisitionCompletionStateEnum AcquisitionCompletionStateEnum {
      get { return acquisitionCompletionStateEnum_; }
      set {
        acquisitionCompletionStateEnum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AcquisitionCompletionStateReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AcquisitionCompletionStateReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AcquisitionCompletionStateEnum != other.AcquisitionCompletionStateEnum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AcquisitionCompletionStateEnum != 0) hash ^= AcquisitionCompletionStateEnum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AcquisitionCompletionStateEnum != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AcquisitionCompletionStateEnum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AcquisitionCompletionStateEnum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AcquisitionCompletionStateEnum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AcquisitionCompletionStateReply other) {
      if (other == null) {
        return;
      }
      if (other.AcquisitionCompletionStateEnum != 0) {
        AcquisitionCompletionStateEnum = other.AcquisitionCompletionStateEnum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            acquisitionCompletionStateEnum_ = (global::Ipc.Definitions.AcquisitionCompletionStateReply.Types.AcquisitionCompletionStateEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AcquisitionCompletionStateReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum AcquisitionCompletionStateEnum {
        [pbr::OriginalName("INCOMPLETE")] Incomplete = 0,
        [pbr::OriginalName("STOPPED")] Stopped = 1,
        [pbr::OriginalName("FAILED")] Failed = 2,
        [pbr::OriginalName("SUCCESSFULLY_COMPLETED")] SuccessfullyCompleted = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
